apiVersion: v2
name: gocd-prometheus-exporter
description: A Helm chart to install prometheus exporter for CI/CD server GoCD
appVersion: "v0.1.2"
version: 0.1.21
home: https://github.com/nikhilsbhat/gocd-prometheus-exporter
sources:
  - https://github.com/nikhilsbhat/gocd-prometheus-exporter/tree/master/charts/gocd-prometheus-exporter
keywords:
  - metrics
  - gocd
  - monitoring
maintainers:
  - name: nikhil bhat
    email: nikhilsbhat93@gmail.com
    url: https://nikhilsbhat.github.io
type: application
