apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gocd-prometheus-exporter.fullname" . }}-secret
  labels:
    {{- include "gocd-prometheus-exporter.labels" . | nindent 4 }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  GOCD_USERNAME: {{ .Values.exporter_config.username | b64enc }}
  {{- if not .Values.exporter_config.bearer_token }}
  GOCD_PASSWORD: {{ .Values.exporter_config.password | b64enc }}
  {{- end }}
  {{- if .Values.exporter_config.bearer_token }}
  GOCD_BEARER_TOKEN: {{ .Values.exporter_config.bearer_token | b64enc }}
  {{- end }}