apiVersion: v1
kind: Service
metadata:
  name: {{ include "gocd-prometheus-exporter.fullname" . }}
  labels:
    {{- include "gocd-prometheus-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      protocol: TCP
  selector:
    {{- include "gocd-prometheus-exporter.selectorLabels" . | nindent 4 }}
