{
 "title": "gocd-monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "gocd agents count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gocd_agents_count" }
   ]
  },
  {
   "title": "agents disconnected",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gocd_agent_down", "legendFormat": "{{ id }}" }
   ]
  },
  {
   "title": "agent disk space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "gocd_agent_disk_space/1024/1024/1024",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "server health status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gocd_server_health", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "pipeline size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    { "expr": "gocd_pipeline_size/1024/1024", "legendFormat": "{{pipeline_path}}" }
   ]
  }
 ]
}